Chg 280536 prevent approve reject requests changing model data
DEFRA/rpa-mit-invoice pull request #53
Opened 2024-02-02 13:05 UTC by yinkacocky

2024-02-05 11:18 UTC, andygibbonsdefra requested changes
IsExistingEntityEqualUpdatedInvoice looks like it doesn't check the whole model for equality.

I might just allow Status and ApprovedBy and Approved to be changed from existing as a different, possibly safer approach.

Also double check that it covers all PUT endpoints. (Does this just check gatekeep the Bulk endpoint?)

2024-02-05 11:18 UTC, andygibbonsdefra commented on EST.MIT.Invoice.Api/Services/PaymentsBatch/PaymentRequestsBatchService.cs
> +            if (IsExistingEntityEqualUpdatedInvoice(existingEntity, invoice))
This code looks to only be hooked on to the 'Bulk' endpoint. Should be on all PUT endpoints that that could change the persisted Invoice data maliciously.

2024-02-05 11:18 UTC, andygibbonsdefra commented on EST.MIT.Invoice.Api/Services/PaymentsBatch/PaymentRequestsBatchService.cs
> -	public async Task<PaymentRequestsBatch> CreateAsync(PaymentRequestsBatch invoice, LoggedInUser loggedInUser)
Try to avoid non-code-change changes in the PR. It makes it harder to review.

2024-02-05 12:32 UTC, yinkacocky commented
> IsExistingEntityEqualUpdatedInvoice looks like it doesn't check the whole model for equality.
> **I don't think it needs to check the whole model for equality. For instance DateTime properties like Created and Updated will throw an error because on comparing the dates they would not be exact match.** 
> I might just allow Status and ApprovedBy and Approved to be changed from existing as a different, possibly safer approach.
> **I don't quite understand you here. Can you shed more light**
> Also double check that it covers all PUT endpoints. (Does this just check gatekeep the Bulk endpoint?)
There's only one Put Endpoint in the InvoiceApi  with the UpdateInvoice method that calls the UpdateAsync  method
Can you again shed more light on this

2024-02-05 12:46 UTC, yinkacocky commented on EST.MIT.Invoice.Api/Services/PaymentsBatch/PaymentRequestsBatchService.cs
> +            if (IsExistingEntityEqualUpdatedInvoice(existingEntity, invoice))
Can you explain further, I don't quite get you

2024-02-05 14:42 UTC, yinkacocky commented
Hi Andy,
Hope your getting better
I have replied to your review on Github. Can you have a look at my response please. Thanks

From: andygibbonsdefra ***@***.***>
Sent: Monday, February 5, 2024 11:19 AM
To: DEFRA/rpa-mit-invoice ***@***.***>
Cc: Adetunji, Henry ***@***.***>; Author ***@***.***>
Subject: Re: [DEFRA/rpa-mit-invoice] Chg 280536 prevent approve reject requests changing model data (PR #53)


@andygibbonsdefra requested changes on this pull request.

IsExistingEntityEqualUpdatedInvoice looks like it doesn't check the whole model for equality.

I might just allow Status and ApprovedBy and Approved to be changed from existing as a different, possibly safer approach.

Also double check that it covers all PUT endpoints. (Does this just check gatekeep the Bulk endpoint?)

________________________________

In EST.MIT.Invoice.Api/Services/PaymentsBatch/PaymentRequestsBatchService.cs<https://github.com/DEFRA/rpa-mit-invoice/pull/53#discussion_r1478010969>:

> @@ -103,12 +104,18 @@ public async Task<PaymentRequestsBatch> UpdateAsync(PaymentRequestsBatch invoice



         if (InvoiceIsBeingApprovedOrRejected(existingEntity, invoice))

         {

-            invoice.Approved = DateTime.Now;

-            invoice.ApprovedBy = loggedInUser.UserId; // not sure what we should be storing here, the id the email or something else

+            if (IsExistingEntityEqualUpdatedInvoice(existingEntity, invoice))

This code looks to only be hooked on to the 'Bulk' endpoint. Should be on all PUT endpoints that that could change the persisted Invoice data maliciously.

________________________________

In EST.MIT.Invoice.Api/Services/PaymentsBatch/PaymentRequestsBatchService.cs<https://github.com/DEFRA/rpa-mit-invoice/pull/53#discussion_r1478012023>:

>          {

             return new List<PaymentRequestsBatch>();

         }

     }



-       public async Task<PaymentRequestsBatch> CreateAsync(PaymentRequestsBatch invoice, LoggedInUser loggedInUser)

Try to avoid non-code-change changes in the PR. It makes it harder to review.

-
Reply to this email directly, view it on GitHub<https://github.com/DEFRA/rpa-mit-invoice/pull/53#pullrequestreview-1862435765>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYA4QPNLP25RZYCRDXLIAJDYSC5Y3AVCNFSM6AAAAABCWU544SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRSGQZTKNZWGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Department for Environment, Food and Rural Affairs (Defra) This email and any attachments is intended for the named recipient only. If you have received it in error you have no authority to use, disclose, store or copy any of its contents and you should destroy it and inform the sender. Whilst this email and associated attachments will have been checked for known viruses whilst within Defra systems we can accept no responsibility once it has left our systems. Communications on Defra's computer systems may be monitored and/or recorded to secure the effective operation of the system and for other lawful purposes.

2024-02-09 08:15 UTC, yinkacocky commented on EST.MIT.Invoice.Api/Services/PaymentsBatch/PaymentRequestsBatchService.cs
> +            if (IsExistingEntityEqualUpdatedInvoice(existingEntity, invoice))
According to the user story, there's only one applicable Endpoint which is the InvoicePutEndPoints.cs. in the Invoice.Api project. Please  Can you have a look at the code and advice where other applicable Endpoints might be?

2024-05-01 15:20 UTC, closed without merging